### PR TITLE
Implement new version of TamperChrome using debugger API

### PR DESCRIPTION
**Pull request by sirdarckcat**
Implementation of TamperChrome using the debugger API instead of webRequestBlocking.

### CODE REVIEW

**Comment by ywmail** [comment]
need this to modify response body.

**Comment by SteelCrow** [comment]
@sirdarckcat, does v2 is working? I try to compile it, and succed after some changes, but I broke my head around how ui component sync with extension, no code for communication, no manifest... May you help me a little bit?

**Comment by sirdarckcat** [comment]
its not working yet, we are blocked on things happening :)

it might be possible to use this in 6-12 weeks
https://github.com/google/tamperchrome/issues/31#issuecomment-692472435

**Comment by sirdarckcat** [comment]
https://chromiumdash.appspot.com/commits?commit=3f2db84c2369ce9e358da246f8e955428867f291 claims this came out in 87 https://chromereleases.googleblog.com/2020/12/stable-channel-update-for-desktop.html which came out a few days ago.

**Comment by sirdarckcat** [comment]
Fetch.fulfillRequest seems to be broken for some reason. I'll debug this later and file a bug with Chrome once I have a version working to modify requests, even if modifying responses doesn't work.

**Comment by sirdarckcat** [comment]
UI Current Status (not functional yet, just UI implemented):
screenshot of tamperchrome v2

API Current Status:
 - Request interception and modification works
 - Response interception and modification is broken (Chrome bug)

TODO list:
 - make request-list work
   - [ ] keep track of all requests passing through (from [here](https://github.com/sirdarckcat/tamperchrome/blob/70fe2ba5a462935157ea9bd6f965a8b0a7a53697/v2/ui/src/interceptor.service.ts#L21)) in an array
   - [ ] propagate that array to the UI (make [this](https://github.com/sirdarckcat/tamperchrome/blob/70fe2ba5a462935157ea9bd6f965a8b0a7a53697/v2/ui/src/app/request-list/request-list.component.ts#L34) read from the service instead of constants).
 - make request-filter work
   - [ ] propagate the domains/methods from the list (see request-list above) to the UI (make [this](https://github.com/sirdarckcat/tamperchrome/blob/70fe2ba5a462935157ea9bd6f965a8b0a7a53697/v2/ui/src/app/request-filter/request-filter.component.ts#L33) read from service)
   - [ ] filter the requests on the interceptor service based on the [`.filters`](https://github.com/sirdarckcat/tamperchrome/blob/70fe2ba5a462935157ea9bd6f965a8b0a7a53697/v2/ui/src/interceptor.service.ts#L8) property.
  - make request-editor work
    - [ ] when the user selects a request from request-list, populate the request editor with it
    - [ ] load the values from the request editor from the [active request](https://github.com/sirdarckcat/tamperchrome/blob/70fe2ba5a462935157ea9bd6f965a8b0a7a53697/v2/ui/src/app/request-editor/request-editor.component.ts#L28)
  - make request-body work
    - [ ] same as request-editor
  - make the submit button work
    - [ ] serialize the headers/method/url/body and pass it back to the API

**Comment by sirdarckcat** [comment]
Bugs:
 - [ ] pressing backspace to delete a chip unfocuses the filter
 - [ ] closing the window doesnt detach the debugger

**Comment by sirdarckcat** [comment]
Current status:
The request editor shows the requests when selected. The send button still doesn't work.

Bugs:
 - [ ] clicking on the list doesn't actually select the request (focus event doesn't seem to trigger a change on selected value)
 - [ ] hex editor doesn't work yet

**Pull request merged**
